//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.ChivaConfigurationVRPatform
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:db059507-3803-44ab-9659-2c6c7ad847c2
    public partial class SourceTree
    {
        
        public const string NAME = "SourceTree";
        
        [SerializeField()]
        public TreeNode TreeNode;
        
        [SerializeField()]
        public UnityEngine.RectTransform Content;
        
        [SerializeField()]
        public UnityEngine.UI.Button AddMainNodeBtn;
        
        [SerializeField()]
        public UnityEngine.UI.InputField searchInputField;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle searchBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button FinishBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button CancleBtn;
        
        private SourceTreeData mPrivateData = null;
        
        public SourceTreeData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new SourceTreeData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TreeNode = null;
            Content = null;
            AddMainNodeBtn = null;
            searchInputField = null;
            searchBtn = null;
            FinishBtn = null;
            CancleBtn = null;
            mData = null;
        }
    }
}
