//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.ChivaConfigurationVRPatform
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:b35f203a-546c-4977-9dca-2af29e6c6a18
    public partial class SourceTree
    {
        
        public const string NAME = "SourceTree";
        
        private SourceTreeData mPrivateData = null;
        
        public SourceTreeData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new SourceTreeData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            mData = null;
        }
    }
}
